[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["ay136416 <<>>"]
description = ""
name = "thediscordmathbot"
version = "0.0.1"
[tool.poetry.dependencies]
discord = "^1.7.3"
discord-py-slash-command = "^3.0.1"
"dislash.py" = "^1.4.9"
nextcord = {git = "https://github.com/nextcord/nextcord.git"}
python = "^3.8"
typing-extensions = "^3.10.0"
orjson = "^3.6.3"
sqldict = {git = "https://github.com/rf20008/sqldict.git"}
python-dotenv = "^0.19.1"
[tool.poetry.dev-dependencies]
