[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["ay136416 <<>>"]
description = ""
name = "thediscordmathbot"
version = "0.0.1"
[tool.poetry.dependencies]
discord-py-slash-command = "^3.0.1"
nextcord = "^2.0.0-alpha.1"
python = "^3.8"
typing-extensions = "^3.10.0"
discord = "^1.7.3"
[tool.poetry.dev-dependencies]
