[tool.poetry]
name = "thediscordmathbot"
version = "0.1.0"
description = ""
authors = ["ay136416 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = "^1.7.3"
discord-py-slash-command = "^3.0.1"
typing-extensions = "^3.10.0"
orjson = "^3.6.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
